### PR TITLE
Implement Azure OpenAI Service

### PR DESCRIPTION
**Pull request by ncface**
Implements configurations to work with Azures OpenAI service.

### CODE REVIEW

**Comment by OkGoDoIt** [comment]
I applied for access to the Azure OpenAI service but was denied, so I have no way to validate or test this.  But I would love to support it.  Do you have access yourself?

**Comment by ncface** [comment]
Yes, I have access to the service in a subscription through a project of my company. The main difference to the direct OpenAI-API is, that the api-version in the URI is mandatory and the api-key header is used. 
It would be great if I can use this project for consuming the Azure OpenAI Service in a project.

**Comment by gotmike** [comment]
> I applied for access to the Azure OpenAI service but was denied, so I have no way to validate or test this. But I would love to support it. Do you have access yourself?

currently only supports "managed" accounts --> https://learn.microsoft.com/en-us/legal/cognitive-services/openai/limited-access?context=%2Fazure%2Fcognitive-services%2Fopenai%2Fcontext%2Fcontext

> Azure OpenAI requires registration and is currently only available to managed customers and partners working with Microsoft account teams.

**Comment by ncface** [comment]
> does this change take the place of the original endpoint?

No, the OpenAI-API-URL is still set as default. My intention was to additionally support the Azure Service.
If you take a closer look into the code changes, there is only added a separate header with the same API-Key like for the OpenAI API itself (so now are both headers sent always) and the version as parameter to the Endpoint-URL (if not set, as per default, nothing is added to the end of the endpoint-URL).

**Comment by ncface** [comment]
> > I applied for access to the Azure OpenAI service but was denied, so I have no way to validate or test this. But I would love to support it. Do you have access yourself?
> 
> 
> 
> currently only supports "managed" accounts --> https://learn.microsoft.com/en-us/legal/cognitive-services/openai/limited-access?context=%2Fazure%2Fcognitive-services%2Fopenai%2Fcontext%2Fcontext
> 
> 
> 
> > Azure OpenAI requires registration and is currently only available to managed customers and partners working with Microsoft account teams.
> 
> 

Yeah, even our Microsoft customer success manager didn't had access to the API. So it seems like they keep access to it as a shortage...

**Comment by OkGoDoIt** [comment]
Thanks for your help with this.  Since I can't test it myself, can you please add some integration tests that use the Azure endpoint?  I'll still need to disable them on my end until I can get access, but it would be good to have tests implemented and run on your end.

**Comment by ncface** [comment]
Thank you @OkGoDoIt , Great!

**Pull request merged**
