### PR TITLE
commenting AssemblyOriginatorKeyFile

### PR DESCRIPTION
**Pull request by gotmike**
this line prevents non-originators from building/using code

### CODE REVIEW

**Comment by OkGoDoIt** [comment]
I think this is needed to accomplish #25 ?  But maybe there's a better way?

**Comment by gotmike** [comment]
the reference is to a local file on your hard drive, so i don't think it's useful to anyone else, i think you can use csproj.user locally and not commit...
https://stackoverflow.com/questions/69165785/at-which-location-path-does-visual-studio-2019-creates-csproj-user-file

**Comment by OkGoDoIt** [comment]
Ok, I fixed this in https://github.com/OkGoDoIt/OpenAI-API-dotnet/commit/b66b7b60c93502fdca9e083c203d84f26626cae2 by pulling the assembly signing stuff into a local `csproj.user` file.  Please confirm that this fixes your problem @gotmike

**Comment by gotmike** [comment]
ok changes u made seem to fix. closing.

**Pull request closed without merging**
